### ISSUE TITLE
501(c)(3) status No longer Pending

### ISSUE THREAD

**Issue by DavidKowarsky** [Worlds-Elsewhere/worlds-elsewhere.com#100]
I proposed changes to the Support us page, but anywhere where we discuss our 501(c)(3) status as pending, we should remove the reference to it being pending and replace with the following. 

---
Worlds Elsewhere Theatre Company Inc. is recognized as a tax-exempt organization under section 501(c)(3) of the Internal Revenue Code. Contributions to organizations with 501(c)(3) status may be tax deductible to U.S. Taxpayers. Please consult your tax advisor to determine the tax-deductibility of any contributions.

**Comment by pigsflew** [comment]
I updated the Support Us page, as well as the Social Media Assistant listing that is still up, and the Temperance listing which may be reused in the future.
