### ISSUE TITLE
G-Suite site verification Code.

### ISSUE THREAD

**Issue by DavidKowarsky** [Worlds-Elsewhere/worlds-elsewhere.com#101]
Please ping me when this is complete. 

Code is below
--
google-site-verification=yeE_KJKrFRNntwg9ReJfJexeIHi9eSKqUp0uGA5LgWA
--
Instructions Copy-pasted from Google.

In a second browser window or tab, sign in to your domain host account. Help me find my host.
Go to your domain’s DNS records. The page might be called something like DNS Management, Name Server Management, Control Panel, or Advanced Settings.
Select the option to add a new record.
5. Add your TXT record
For the record type, select TXT.
In the Name/Host/Alias field, enter @ or leave it blank.

Your host can require you to enter your domain, which looks like yourdomain.com, into this field.

Your other DNS records might indicate what you should enter.

In the Time to Live (TTL) field, enter 86400 or leave the default.
In the Value/Answer/Destination field, paste the TXT verification record you copied above.
Save the record.
Note: If you see a warning message about changing your DNS settings, disregard it. Adding the TXT record won’t damage your website or DNS settings.

**Comment by pigsflew** [comment]
Done!
