### ISSUE TITLE
Work With Us -> Crew Call: Banner Artist

### ISSUE THREAD

**Issue by pigsflew** [Worlds-Elsewhere/worlds-elsewhere.com#48]
Make a page for this with details; will be posting on Social tomorrow (5/19).

Draft copy & run by WETC board & Laura

May borrow theme info re: summer cabaret.

**Comment by DavidKowarsky** [comment]
N.B. Verbiage should involve "We would like to commission banner art" rather than any implication that this is a FT/PT position per se.
