### ISSUE TITLE
Add Resources Section to Website

### ISSUE THREAD

**Issue by melayneseahawk** [Worlds-Elsewhere/worlds-elsewhere.com#62]
Add Resources section to website and put Juneteenth Theatre List under that heading; leave link to Theatre List on homepage until end of June

**Comment by pigsflew** [comment]
My understanding (please correct if wrong?)

- On July 1
  - Change the title of the page to "Black Theatres & Theatre Organization Listing (USA)"
  - Change the link to "/resources/black-theatres-usa" (will maintain the existing link as a redirect for existing social media posts)
  - Remove the homepage promo
  - Add the "Resources" section to link to the page, and link it into the site.

**Comment by pigsflew** [comment]
Open questions:

1. "Resources section" is vague: Is this a new page? Is it just a permanent spot in the Home page? Or perhaps the About page?
2. If the new "Resources" section is a short page, will it be linked in the Nav? Or off of an existing page?
3. Should I await copy? Or draft my own?

**Comment by pigsflew** [comment]
My suggestion: would actually be to just make a semi-permanent spot in the homepage, until we have other resources we're providing, as a new header after "Support", before "Keep in Touch"

Suggested copy:

> ## ✊🏽 WETC Supports BLM and Black Artists
>
> Since Juneteenth 2021, Worlds Elsewhere has maintained a list of theatres and theatre organizations in the USA that bring Black stories to the stage, told by Black playwrights, performed by Black artists.
>
> [***See the List***](https://worlds-elsewhere.com/pages/juneteenth-2021)

Once we have other resources on offer, we can gather them together on an actual "Resources" page and add it at the top level to the Nav header.

**Comment by melayneseahawk** [comment]
Yeah, this all looks good
