### ISSUE TITLE
The program of Lysistrata is unavailable

### ISSUE THREAD

**Issue by nikolai-semenov** [Worlds-Elsewhere/worlds-elsewhere.com#9]
[The program of Lysistrata](https://worlds-elsewhere.com/plays/lysistrata) mentioned in [the stream description](https://www.youtube.com/watch?v=nOQqgwHmij8) is unavailable. Perhaps, the correct link is https://worlds-elsewhere.com/shows/2020.10/lysistrata.

**Comment by pigsflew** [comment]
Thank you for reaching out! It should be updated now.
